package com.izzedineeita.mihrab.constants;

public interface Constants {

    String PREF_CITY_POSITION_SELECTED = "PREF_CITY_POSITION_SELECTED";
    String PREF_THEM_POSITION_SELECTED = "PREF_THEM_POSITION_SELECTED";

    String PREF_IQAMH_FAJR_RELATIVE_TIME_SELECTED = "PREF_IQAMH_FAJR_RELATIVE_TIME_SELECTED";
    String PREF_IQAMH_SUNRISE_RELATIVE_TIME_SELECTED = "PREF_IQAMH_SUNRISE_RELATIVE_TIME_SELECTED";
    String PREF_IQAMH_DHOHR_RELATIVE_TIME_SELECTED = "PREF_IQAMH_DHOHR_RELATIVE_TIME_SELECTED";
    String PREF_IQAMH_ASR_RELATIVE_TIME_SELECTED = "PREF_IQAMH_ASR_RELATIVE_TIME_SELECTED";
    String PREF_IQAMH_MAGHRIB_RELATIVE_TIME_SELECTED = "PREF_IQAMH_MAGHRIB_RELATIVE_TIME_SELECTED";
    String PREF_IQAMH_ISHA_RELATIVE_TIME_SELECTED = "PREF_IQAMH_ISHA_RELATIVE_TIME_SELECTED";

    String PREF_IQAMH_FAJR_CONSTANT_TIME_SELECTED = "PREF_IQAMH_FAJR_CONSTANT_TIME_SELECTED";
    String PREF_IQAMH_SUNRISE_CONSTANT_TIME_SELECTED = "PREF_IQAMH_SUNRISE_CONSTANT_TIME_SELECTED";
    String PREF_IQAMH_DHOHR_CONSTANT_TIME_SELECTED = "PREF_IQAMH_DHOHR_CONSTANT_TIME_SELECTED";
    String PREF_IQAMH_ASR_CONSTANT_TIME_SELECTED = "PREF_IQAMH_ASR_CONSTANT_TIME_SELECTED";
    String PREF_IQAMH_MAGHRIB_CONSTANT_TIME_SELECTED = "PREF_IQAMH_MAGHRIB_CONSTANT_TIME_SELECTED";
    String PREF_IQAMH_ISHA_CONSTANT_TIME_SELECTED = "PREF_IQAMH_ISHA_CONSTANT_TIME_SELECTED";


    String PREF_MASGED_NAME = "PREF_MASGED_NAME";


    String PREF_FAJER_SOUND_AZAN = "PREF_FAJER_SOUND_AZAN";
    String PREF_FAJER_SOUND_AZAN_PATH = "PREF_FAJER_SOUND_AZAN_PATH";
    String PREF_FAJER_SOUND_IQAMAH = "PREF_FAJER_SOUND_IQAMAH";
    String PREF_FAJER_SOUND_IQAMAH_PATH = "PREF_FAJER_SOUND_IQAMAH_PATH";
    String PREF_FAJER_RELATIVE = "PREF_FAJER_RELATIVE";
    String PREF_FAJER_IQAMAH_RELATIVE = "PREF_FAJER_IQAMAH_RELATIVE";
    String PREF_FAJER_CONSTANT = "PREF_FAJER_CONSTANT";
    String PREF_FAJER_IQAMAH_CONSTANT = "PREF_FAJER_IQAMAH_CONSTANT";
    String PREF_FAJER_AZKAR_SHOW_IN = "PREF_FAJER_AZKAR_SHOW_IN";
    String PREF_FAJER_AZKAR_SHOW_TIME = "PREF_FAJER_AZKAR_SHOW_TIME";
    String PREF_FAJER_SOUND_CLOSE_PHONE_PATH = "PREF_FAJER_SOUND_CLOSE_PHONE_PATH";

    String PREF_SUNRISE_SOUND_AZAN = "PREF_SUNRISE_SOUND_AZAN";
    String PREF_SUNRISE_SOUND_IQAMAH = "PREF_SUNRISE_SOUND_IQAMAH";
    String PREF_SUNRISE_RELATIVE = "PREF_SUNRISE_RELATIVE";
    String PREF_SUNRISE_IQAMAH_RELATIVE = "PREF_SUNRISE_IQAMAH_RELATIVE";
    String PREF_SUNRISE_CONSTANT = "PREF_SUNRISE_CONSTANT";
    String PREF_SUNRISE_IQAMAH_CONSTANT = "PREF_SUNRISE_IQAMAH_CONSTANT";
    String PREF_SUNRISE_AZKAR_SHOW_IN = "PREF_SUNRISE_AZKAR_SHOW_IN";
    String PREF_SUNRISE_AZKAR_SHOW_TIME = "PREF_SUNRISE_AZKAR_SHOW_TIME";


    String PREF_DHOHR_SOUND_AZAN = "PREF_DHOHR_SOUND_AZAN";
    String PREF_DHOHR_SOUND_IQAMAH = "PREF_DHOHR_SOUND_IQAMAH";
    String PREF_DHOHR_RELATIVE = "PREF_DHOHR_RELATIVE";
    String PREF_DHOHR_IQAMAH_RELATIVE = "PREF_DHOHR_IQAMAH_RELATIVE";
    String PREF_DHOHR_CONSTANT = "PREF_DHOHR_CONSTANT";
    String PREF_DHOHR_IQAMAH_CONSTANT = "PREF_DHOHR_IQAMAH_CONSTANT";
    String PREF_DHOHR_AZKAR_SHOW_IN = "PREF_DHOHR_AZKAR_SHOW_IN";
    String PREF_DHOHR_AZKAR_SHOW_TIME = "PREF_DHOHR_AZKAR_SHOW_TIME";
    String PREF_DHOHR_SOUND_AZAN_PATH = "PREF_DHOHR_SOUND_AZAN_PATH";
    String PREF_DHOHR_SOUND_IQAMAH_PATH = "PREF_DHOHR_SOUND_IQAMAH_PATH";
    String PREF_DHOHR_SOUND_CLOSE_PHONE_PATH = "PREF_DHOHR_SOUND_CLOSE_PHONE_PATH";

    String PREF_ASR_SOUND_AZAN = "PREF_ASR_SOUND_AZAN";
    String PREF_ASR_SOUND_IQAMAH = "PREF_ASR_SOUND_IQAMAH";
    String PREF_ASR_RELATIVE = "PREF_ASR_RELATIVE";
    String PREF_ASR_IQAMAH_RELATIVE = "PREF_ASR_IQAMAH_RELATIVE";
    String PREF_ASR_CONSTANT = "PREF_ASR_CONSTANT";
    String PREF_ASR_IQAMAH_CONSTANT = "PREF_ASR_IQAMAH_CONSTANT";
    String PREF_ASR_AZKAR_SHOW_IN = "PREF_ASR_AZKAR_SHOW_IN";
    String PREF_ASR_AZKAR_SHOW_TIME = "PREF_ASR_AZKAR_SHOW_TIME";
    String PREF_ASR_SOUND_AZAN_PATH = "PREF_ASR_SOUND_AZAN_PATH";
    String PREF_ASR_SOUND_IQAMAH_PATH = "PREF_ASR_SOUND_IQAMAH_PATH";
    String PREF_ASR_SOUND_CLOSE_PHONE_PATH = "PREF_ASR_SOUND_CLOSE_PHONE_PATH";

    String PREF_MAGHRIB_SOUND_AZAN = "PREF_MAGHRIB_SOUND_AZAN";
    String PREF_MAGHRIB_SOUND_IQAMAH = "PREF_MAGHRIB_SOUND_IQAMAH";
    String PREF_MAGHRIB_RELATIVE = "PREF_MAGHRIB_RELATIVE";
    String PREF_MAGHRIB_IQAMAH_RELATIVE = "PREF_MAGHRIB_IQAMAH_RELATIVE";
    String PREF_MAGHRIB_CONSTANT = "PREF_MAGHRIB_CONSTANT";
    String PREF_MAGHRIB_IQAMAH_CONSTANT = "PREF_MAGHRIB_IQAMAH_CONSTANT";
    String PREF_MAGHRIB_AZKAR_SHOW_IN = "PREF_MAGHRIB_AZKAR_SHOW_IN";
    String PREF_MAGHRIB_AZKAR_SHOW_TIME = "PREF_MAGHRIB_AZKAR_SHOW_TIME";
    String PREF_MAGHRIB_SOUND_AZAN_PATH = "PREF_MAGHRIB_SOUND_AZAN_PATH";
    String PREF_MAGHRIB_SOUND_IQAMAH_PATH = "PREF_MAGHRIB_SOUND_IQAMAH_PATH";
    String PREF_MAGHRIB_SOUND_CLOSE_PHONE_PATH = "PREF_MAGHRIB_SOUND_CLOSE_PHONE_PATH";


    String PREF_ISHA_SOUND_AZAN = "PREF_ISHA_SOUND_AZAN";
    String PREF_ISHA_SOUND_IQAMAH = "PREF_ISHA_SOUND_IQAMAH";
    String PREF_ISHA_RELATIVE = "PREF_ISHA_RELATIVE";
    String PREF_ISHA_IQAMAH_RELATIVE = "PREF_ISHA_IQAMAH_RELATIVE";
    String PREF_ISHA_CONSTANT = "PREF_ISHA_CONSTANT";
    String PREF_ISHA_IQAMAH_CONSTANT = "PREF_ISHA_IQAMAH_CONSTANT";
    String PREF_ISHA_AZKAR_SHOW_IN = "PREF_ISHA_AZKAR_SHOW_IN";
    String PREF_ISHA_AZKAR_SHOW_TIME = "PREF_ISHA_AZKAR_SHOW_TIME";
    String PREF_ISHA_SOUND_AZAN_PATH = "PREF_ISHA_SOUND_AZAN_PATH";
    String PREF_ISHA_SOUND_IQAMAH_PATH = "PREF_ISHA_SOUND_IQAMAH_PATH";
    String PREF_ISHA_SOUND_CLOSE_PHONE_PATH = "PREF_ISHA_SOUND_CLOSE_PHONE_PATH";


    String PREF_CLOSE_PHONE_NOTIFICATION_SOUND = "PREF_CLOSE_PHONE_NOTIFICATION_SOUND";
    String PREF_CLOSE_NOTIFICATION_SOUND_FAJR = "PREF_CLOSE_NOTIFICATION_SOUND_FAJR";
    String PREF_CLOSE_NOTIFICATION_SOUND_SHROUK = "PREF_CLOSE_NOTIFICATION_SOUND_SHROUK";
    String PREF_CLOSE_NOTIFICATION_SOUND_DUHR = "PREF_CLOSE_NOTIFICATION_SOUND_DUHR";
    String PREF_CLOSE_NOTIFICATION_SOUND_ASR = "PREF_CLOSE_NOTIFICATION_SOUND_ASR";
    String PREF_CLOSE_NOTIFICATION_SOUND_MAGHRIB = "PREF_CLOSE_NOTIFICATION_SOUND_MAGHRIB";
    String PREF_CLOSE_NOTIFICATION_SOUND_ISHA = "PREF_CLOSE_NOTIFICATION_SOUND_ISHA";
    String PREF_CLOSE_NOTIFICATION_SOUND_GOMAA = "PREF_CLOSE_NOTIFICATION_SOUND_GOMAA";
    String PREF_CLOSE_NOTIFICATION_SCREEN = "PREF_CLOSE_NOTIFICATION_SCREEN";
    String PREF_CLOSE_NOTIFICATION_SCREEN_GOMAA = "PREF_CLOSE_NOTIFICATION_SCREEN_GOMAA";

    String PREF_HIDE_PULPIT_ADS_BOX = "PREF_HIDE_PULPIT_ADS_BOX";
    
    // Text ads font size, movement speed, and color preferences
    String PREF_TEXT_ADS_FONT_SIZE = "PREF_TEXT_ADS_FONT_SIZE";
    String PREF_TEXT_ADS_MOVEMENT_SPEED = "PREF_TEXT_ADS_MOVEMENT_SPEED";
    String PREF_TEXT_ADS_COLOR = "PREF_TEXT_ADS_COLOR";

    String PREF_CLOSE_PHONE_ALERT_URDU = "PREF_CLOSE_PHONE_ALERT_URDU";
    String PREF_CLOSE_PHONE_ALERT_ARABIC = "PREF_CLOSE_PHONE_ALERT_ARABIC";
    String PREF_CLOSE_PHONE_ALERT_ENGLISH = "PREF_CLOSE_PHONE_ALERT_ENGLISH";
    String PREF_CLOSE_PHONE_ALERT_SHOW_BEFORE_IQAMH = "PREF_CLOSE_PHONE_ALERT_SHOW_BEFORE_IQAMH";


    String PREF_FAJR_TIME = "PREF_FAJR_TIME";
    String PREF_SUNRISE_TIME = "PREF_SUNRISE_TIME";
    String PREF_DHOHR_TIME = "PREF_DHOHR_TIME";
    String PREF_ASR_TIME = "PREF_ASR_TIME";
    String PREF_MAGHRIB_TIME = "PREF_MAGHRIB_TIME";
    String PREF_ISHA_TIME = "PREF_ISHA_TIME";

    String PREF_FAJR_TIME_24 = "PREF_FAJR_TIME_24";
    String PREF_SUNRISE_TIME_24 = "PREF_SUNRISE_TIME_24";
    String PREF_DHOHR_TIME_24 = "PREF_DHOHR_TIME_24";
    String PREF_ASR_TIME_24 = "PREF_ASR_TIME_24";
    String PREF_MAGHRIB_TIME_24 = "PREF_MAGHRIB_TIME_24";
    String PREF_ISHA_TIME_24 = "PREF_ISHA_TIME_24";


    String PREF_SHOW_KATEB = "PREF_SHOW_KATEB";
    String PREF_SHOW_KATEB_TIME = "PREF_SHOW_KATEB_TIME";

    String PREF_FAJR_SHOW_ALKHUSHUE = "PREF_FAJR_SHOW_ALKHUSHUE";
    String PREF_SUNRISE_SHOW_ALKHUSHUE = "PREF_SUNRISE_SHOW_ALKHUSHUE";
    String PREF_DHOHR_SHOW_ALKHUSHUE = "PREF_DHOHR_SHOW_ALKHUSHUE";
    String PREF_ASR_SHOW_ALKHUSHUE = "PREF_ASR_SHOW_ALKHUSHUE";
    String PREF_MAGHRIB_SHOW_ALKHUSHUE = "PREF_MAGHRIB_SHOW_ALKHUSHUE";
    String PREF_ISHA_SHOW_ALKHUSHUE = "PREF_ISHA_SHOW_ALKHUSHUE";

    String PREF_FAJR_TEXT_ALKHUSHUE = "PREF_FAJR_TEXT_ALKHUSHUE";
    String PREF_SUNRISE_TEXT_ALKHUSHUE = "PREF_SUNRISE_TEXT_ALKHUSHUE";
    String PREF_DHOHR_TEXT_ALKHUSHUE = "PREF_DHOHR_TEXT_ALKHUSHUE";
    String PREF_ASR_TEXT_ALKHUSHUE = "PREF_ASR_TEXT_ALKHUSHUE";
    String PREF_MAGHRIB_TEXT_ALKHUSHUE = "PREF_MAGHRIB_TEXT_ALKHUSHUE";
    String PREF_ISHA_TEXT_ALKHUSHUE = "PREF_ISHA_TEXT_ALKHUSHUE";

    String PREF_FAJR_SHOW_ALKHUSHUE_TIME = "PREF_FAJR_SHOW_ALKHUSHUE_TIME";
    String PREF_SUNRISE_SHOW_ALKHUSHUE_TIME = "PREF_SUNRISE_SHOW_ALKHUSHUE_TIME";
    String PREF_DHOHR_SHOW_ALKHUSHUE_TIME = "PREF_DHOHR_SHOW_ALKHUSHUE_TIME";
    String PREF_ASR_SHOW_ALKHUSHUE_TIME = "PREF_ASR_SHOW_ALKHUSHUE_TIME";
    String PREF_MAGHRIB_SHOW_ALKHUSHUE_TIME = "PREF_MAGHRIB_SHOW_ALKHUSHUE_TIME";
    String PREF_ISHA_SHOW_ALKHUSHUE_TIME = "PREF_ISHA_SHOW_ALKHUSHUE_TIME";

    String PREF_FAJR_SHOW_AZKAR_TIME = "PREF_FAJR_SHOW_AZKAR_TIME";
    String PREF_SUNRISE_SHOW_AZKAR_TIME = "PREF_SUNRISE_SHOW_AZKAR_TIME";
    String PREF_DHOHR_SHOW_AZKAR_TIME = "PREF_DHOHR_SHOW_AZKAR_TIME";
    String PREF_ASR_SHOW_AZKAR_TIME = "PREF_ASR_SHOW_AZKAR_TIME";
    String PREF_MAGHRIB_SHOW_AZKAR_TIME = "PREF_MAGHRIB_SHOW_AZKAR_TIME";
    String PREF_ISHA_SHOW_AZKAR_TIME = "PREF_ISHA_SHOW_AZKAR_TIME";


    String PREF_SENSOR_SHOW = "PREF_SENSOR_SHOW";
    String PREF_HEJRY_INT = "PREF_HEJRY_INT";
    String PREF_HEJRY_INT1 = "PREF_HEJRY_INT1";

    String PREF_CHECK_BOX_2 = "PREF_CHECK_BOX_2";

    String PREF_IS_USER_LOGIN = "PREF_IS_USER_LOGIN";

}
